### ISSUE TITLE
Having the "God" Origin causes the world to turn black at midnight in version 0.6.2. 

### ISSUE THREAD

**Issue by Cookie-Kurokami** [Latokike/lato-origins#10]
And I don't know if the latest version fixes this bug because 0.7.0 crashes my server on startup. So, I guess you could say there's two issues. 

![2021-05-17_17 55 11](https://user-images.githubusercontent.com/66750372/118566479-9376fe00-b739-11eb-8a81-df101f2bf792.png)

Also, how do I turn off the translucency power?

**Comment by latokike** [comment]
The god Origin is likely not going to be updated, because it is not supposed to be accessed unless in creative mode, and is just an overpowered Origin in general.

**Comment by latokike** [comment]
You can't turn off the translucency power. The god origin has been updated recently though.
