### ISSUE TITLE
Modify Behavior doesn't work in datapacks

### ISSUE THREAD

**Issue by SapphireBlyth** [Latokike/lato-origins#13]
The modify behavior power type doesn't seem to work in custom data packs.

The power itself doesn't show any errors in the game's logs after creation, it's even showing on the Origin you made with the power and passing the test when you use the `/origin has power` command from the base Origin mod, but the behavior remains the same for any mob.

Even perfectly copy-pasting the `underwater_allies.json` power into the custom-made power, it still does not seem to work and keep the guardians and drowned hostile towards you.

**Comment by latokike** [comment]
The modify behavior power is just a concept right now, and is not functioning

**Comment by SapphireBlyth** [comment]
It's a shame it isn't yet since it seems like a really great power to mess around with for certain custom-Origins.

Would it be possible to get this working for the next update?

**Comment by latokike** [comment]
The axolotl currently has the drowned act passive towards it, but that has resulted in the axolotl not being able to attack the drowned. The slimeeq acts the same way towards slimes.
