### ISSUE TITLE
Lato-Origins makes AppleSkin think every item is food

### ISSUE THREAD

**Issue by HyperlyBola** [Latokike/lato-origins#14]
I still have this issue where every vanilla item even sticks look like food even when i'm not the iron-golem or trashling, cobblestonian, or iron-golem race. I mentioned this issue on the AppleSkin git a while ago. I'm not sure if the fix is possible yet or not because he said "in the future"
![image](https://user-images.githubusercontent.com/50128850/120247997-0eacd980-c23b-11eb-83a7-53d911bc8d79.png)
This is what he was mentioning in that reply https://github.com/squeek502/AppleSkin/pull/99

**Comment by latokike** [comment]
I don't think that it is currently possible to disable the rendering food yet.

**Comment by latokike** [comment]
This should be fixed when I change origins to eat with just a power, instead of a config and custom item code.

**Comment by latokike** [comment]
This has been fixed with [`6bcd5a4`](https://github.com/Latokike/lato-origins/commit/6bcd5a4202c6cb0107e040579d3f5e2b37df099b)
