### ISSUE TITLE
Tauros grass eat ability causes disconnect on multiplayer server

### ISSUE THREAD

**Issue by TheUnion** [Latokike/lato-origins#17]
Hey,

Recently been messing around with origin mods, for a server, and came across yours - but ran into a pretty big issue. Found out choosing Tauros and using it's grass eat ability causes a disconnect to anyone nearby the user, and their self. From what I can tell, it seems to be a problem with the latoorigins:sound type within it's grass eat ability, as I've noticed the ability works fine in singleplayer, but on multiplayer you never hear the sound play of the grass being ate and disconnect immediately. Re-logging shows the grass has turn to dirt, and the ability did what it should do, but the sound seems to be the problem. I tested this on the most recent version of 0.7.3, and even tested it on 0.5.0. I've removed all mods on the server, excluding LatoOrigins and it's dependencies, but the disconnect still occurs.

**Comment by latokike** [comment]
This should be fixed as now the tauros's `grass_graze` ability uses origin's `play_sound` action instead of lato origin's `sound`
