### ISSUE TITLE
The Astronos needs a rebalancing 

### ISSUE THREAD

**Issue by PedroMeira2006** [Latokike/lato-origins#20]
The primary ability of the astronos is so broken, you can just be imortal forever if you have enough food, i think the starvation damage you take could be increased and health decraesed a little bit more.

**Comment by Pete3R** [comment]
I'd suggest slowness type of thing
Like whenever you would be invulnerable you could not more/you move very slowly and swimming is disabled
The ability also drains food, though as mention you can hold M2 with anything to survive, maybe making it so when you attempt to eat the ability disables itself? 
Just a though

**Comment by latokike** [comment]
I also believe the astronos origin could use rebalancing.

**Comment by latokike** [comment]
They have been rebalanced. You can look at [`f880efa`](https://github.com/Latokike/lato-origins/commit/f880efa38782e71e716ef07ff4330edf4546e18c) for more info on it.
