### ISSUE TITLE
Invalid PowerTypeReference: no power type exists with id "latoorigins:lava_breathing" console spam

### ISSUE THREAD

**Issue by Ch1216** [Latokike/lato-origins#22]
![console spam](https://user-images.githubusercontent.com/68875386/136714733-aab71bab-d3ca-42c0-9766-b20b02911cbc.png)
this is in 1.17.1

**Comment by Ch1216** [comment]
![console spam](https://user-images.githubusercontent.com/68875386/136714684-b5ac2774-f61d-4db9-9613-0603b8d4cd70.png)
it seems that lato origins causes it

**Comment by SanelRyan** [comment]
Can confirm, happening the same with me

**Comment by terpsichora45** [comment]
Same here

**Comment by eggohito** [comment]
I think it might have something to do with the [`LOPowers.java`](https://github.com/Latokike/lato-origins/blob/4a75c04b6f9813fc8c1d42c5a633d73668b746a0/src/main/java/latokike/latoorigins/common/registry/LOPowers.java#L102) class creating a new `PowerTypeReference` for the `latoorigins:lava_breathing` power, which was deleted in commit d32d1f02a8cb4436d60024764461b412b30b909c

**Comment by latokike** [comment]
This has been fixed with the 1.18 update.
