### ISSUE TITLE
console error server thread/warn invalid power type reference

### ISSUE THREAD

**Issue by Killakilla2** [Latokike/lato-origins#23]
using this mod on 1.17.1 and i continually get error in conosole literlaly every 4 seconds:
[20.10 13:55:49] [Server] [Server thread/WARN]: Invalid PowerTypeReference: no power type exists with id "latoorigins:lava_breathing"

**Comment by Ch1216** [comment]
#22 litteraly the previous has the same problem

**Comment by latokike** [comment]
This has been fixed with the 1.18 update.
