### ISSUE TITLE
Origins with certain dietary restrictions cannot fill glass bottles

### ISSUE THREAD

**Issue by twixstix** [Latokike/lato-origins#24]
When a carnivore or custom origin that restricts origins:food attempts to fill a glass bottle with water or dragon breath, nothing will happen. Oddly, vegetarians can use bottles like normal. Adding glass_bottle to ignore_diet.json does seem to fix this, so it might be an issue with bottles being defined as food somehow.

**Comment by latokike** [comment]
I'm currently working on a fix for this.
[`Eating-Tweaks`](https://github.com/Latokike/lato-origins/tree/Eating-Tweaks)

**Comment by latokike** [comment]
This has been fixed with [`6bcd5a4`](https://github.com/Latokike/lato-origins/commit/6bcd5a4202c6cb0107e040579d3f5e2b37df099b)
