### ISSUE TITLE
Common Game Crash

### ISSUE THREAD

**Issue by Plushtime** [Latokike/lato-origins#26]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'latoorigins'!
Exit Code: -1

Every Version of 1.18.1 is currently doing this to a lot of people. Many times reported on sites/reddit/ and the curse forge comments. If a fix could be made or a public word on how to fix it this would help incredibly!

Note: I can send crash report if needed

**Comment by latokike** [comment]
[`2131135`](https://github.com/Latokike/lato-origins/commit/2131135d87aff5c77b4c430801c2969e522b6390) -- fixes incompatibility with Pehkui
