### ISSUE TITLE
Lato Glitch

### ISSUE THREAD

**Issue by TheAzuki** [Latokike/lato-origins#3]
I was playing multiplayer Lato origins with a couple of other mods when my brother had to leave and come back but when i joined back i could no longer use my lato ability

**Comment by latokike** [comment]
Could you provide a log

**Comment by TheAzuki** [comment]
> Could you provide a log

How do I do that?

**Comment by TheAzuki** [comment]
> Could you provide a log

17:52:03.239
Unknown recipe category: dml-refabricated:trial_keystone/dml-refabricated:trial/zombie/trialkeystone_1
17:52:03.239
Unknown recipe category: kiln:firing/kiln:terracotta_from_firing
17:52:03.239
Unknown recipe category: kiln:firing/kiln:blue_glazed_terracotta_from_firing
17:52:03.239
Unknown recipe category: dml-refabricated:trial_keystone/dml-refabricated:trial/ghost/trialkeystone_0
17:52:03.239
Unknown recipe category: kiln:firing/kiln:cracked_nether_bricks_from_firing
17:52:03.239
Unknown recipe category: haema:ritual/haema:rituals/add_level_1
17:52:03.239
Unknown recipe category: dml-refabricated:trial_keystone/dml-refabricated:trial/skeleton/trialkeystone_0
17:52:03.240
Unknown recipe category: dml-refabricated:trial_keystone/dml-refabricated:trial/illager/trialkeystone_2
17:52:03.240
Unknown recipe category: haema:ritual/haema:rituals/change_abilities_0
17:52:03.240
Unknown recipe category: kiln:firing/kiln:brick_from_firing
17:52:03.240
Unknown recipe category: dml-refabricated:trial_keystone/dml-refabricated:trial/skeleton/trialkeystone_1
17:52:03.240
Unknown recipe category: dml-refabricated:trial_keystone/dml-refabricated:trial/nether/trialkeystone_1
17:52:03.240
Unknown recipe category: kiln:firing/kiln:light_gray_glazed_terracotta_from_firing
17:52:03.250
Unknown recipe category: dml-refabricated:trial_keystone/dml-refabricated:trial/slimy/trialkeystone_1
17:52:03.250
Unknown recipe category: kiln:firing/kiln:lime_dye_from_firing
17:52:03.809
Suppressing Sync Recipes!
17:52:03.975
Stopping worker threads
17:52:03.999
Started 12 worker threads

**Comment by TheAzuki** [comment]
There was alot more not sure why it didnt paste

**Comment by TheAzuki** [comment]
In the world it shows the bar but it wont regenerate. I use the lato origin, human soul, and the blacksmith class.

**Comment by latokike** [comment]
I haven't been able to replicate this issue

**Comment by TheAzuki** [comment]
> I haven't been able to replicate this issue

Me and my brother think its because a glitch ive been using to connect over LAN while using another network. I would join the same network as him and wait for the LAN server to pop up, I would then switch to another network and then join him off of the other network.

**Comment by latokike** [comment]
I think this problem is with origins, not lato origins
