### ISSUE TITLE
You can get kicked if you fly as a Astrono

### ISSUE THREAD

**Issue by Ch1216** [Latokike/lato-origins#33]
If you are in a multiplayer server and you start to Sky Swim for ~8-5 seconds you get kicked for flying

You shouldnt be kicked as you are not hacking/cheating the game, as flying is now a normal thing you can do in survival if you are a Astrono

**Comment by latokike** [comment]
Unfortunately, this is not the mod's fault, and so there is nothing I can do to fix it. The only way that I can see this working ou would be to get the server owner to turn off the kick in the server settings.
