### ISSUE TITLE
Incompatibility with Extra Origins Mod

### ISSUE THREAD

**Issue by ConqAra** [Latokike/lato-origins#4]
Finally found the issue! Mod is incompatible with the extra origins mod.

Mod: [Extra Origins](https://github.com/MoriyaShiine/extra-origins)
Log: [https://pastebin.com/qankudty](https://pastebin.com/qankudty)

**Comment by latokike** [comment]
It seems that it is an issue with the latest version of extra origins, as it runs just fine with extraorigins-1.16.5-9

**Comment by ConqAra** [comment]
even if we works with extraorigins-1.16.5-9, it STILL crashes the game while making a new world.

**Comment by Alferinoo** [comment]
Hi there! Even though you may have found the problem, the Lato Origins mod still does not work with any of extra origins for me and I am not really sure why it isn't working. Also, even if I remove the extra origins mod from my server then it still does not work :P

**Comment by latokike** [comment]
Could you post the mods you are using?

**Comment by latokike** [comment]
The two mods work fine for me, so I want to check if it's not Lato Origins crashing the game

**Comment by latokike** [comment]
Could you post a log?

**Comment by Alferinoo** [comment]
> Could you post the mods you are using?

I was using mob origins, extra origins, origins, pehkui and added origins.
