### ISSUE TITLE
Dimensional Beings health reduction

### ISSUE THREAD

**Issue by thunderdrae** [Latokike/lato-origins#8]
I'm not sure if this is intentional or not, but the Dimensional Being only has 6 hearts, despite the health reduction not being listed anywhere in it's ability list, and i can't change it because the thing that adds that health modifier isn't even in the Dimensional Beings File, just wanted to bring this up as i'm confused whether or not it's intentional and it also makes the origin incredibly underpowered and this makes it unchangeable.

**Comment by latokike** [comment]
Thank you for pointing that out, it is the `mist_body` power making the dimensional being weaker, and that is because warping between dimensions is a very strong power if you can get used to it. Instead of taking 4 hearts, I'll switch it to 3 in the next update.
