### ISSUE TITLE
origins:origins:modify_jump in petrification_dummy_modify_jump_power

### ISSUE THREAD

**Issue by MerleTheAvian** [Latokike/lato-origins#9]
I found the following error in the logs of a person:
"latoorigins:petrification_dummy_modify_jump_power" in power file "latoorigins:petrification_dummy": Power type "origins:origins:modify_jump" is not defined.

Due to "origins:**origins:**modify_jump".

**Comment by latokike** [comment]
Thank you for pointing that out, it'll be fixed in the next update
